In [1]:
!pip install langchain faiss-cpu  tiktoken requests

In [4]:
pip install euriai

  Using cached euriai-0.3.3-py3-none-any.whl.metadata (1.9 kB)
Using cached euriai-0.3.3-py3-none-any.whl (5.7 kB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
from langchain.embeddings.base import Embeddings
from langchain.llms.base import LLM
from typing import List, Dict, Any
import requests
import numpy as np
import faiss
import os

In [3]:
import requests
import numpy as np

def generate_embeddings(text: str) :
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNTM3YzM3Zi0xNmFkLTRjZTUtYjRhMC0wNTNjYTIyNzE1YTgiLCJlbWFpbCI6InN1ZGhhbnNodUBldXJvbi5vbmUiLCJpYXQiOjE3NDMyMzkyNTYsImV4cCI6MTc3NDc3NTI1Nn0.HRHeCucOK0hPVZQwyvNoD0GaHarvHNivjJ2l6-xU1HA"
    }
    payload = {
        "input":text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [7]:

from euriai import EuriaiClient
def generate_response(prompt):
    client = EuriaiClient(
        api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNTM3YzM3Zi0xNmFkLTRjZTUtYjRhMC0wNTNjYTIyNzE1YTgiLCJlbWFpbCI6InN1ZGhhbnNodUBldXJvbi5vbmUiLCJpYXQiOjE3NDMyMzkyNTYsImV4cCI6MTc3NDc3NTI1Nn0.HRHeCucOK0hPVZQwyvNoD0GaHarvHNivjJ2l6-xU1HA",
        model="gpt-4.1-nano"  
    )

    response = client.generate_completion(
        prompt=prompt,
        temperature=0,
        max_tokens=300
    )

    print(response)
    return response['choices'][0]["message"]["content"]

In [ ]:
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter


document = TextLoader("sudhanshuinfo.txt").load()
document

[Document(metadata={'source': 'sudhanshuinfo.txt'}, page_content="\nMaking an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.\n\nThe Entrepreneur and Teacher: Sudhanshu's Dual Legacy\nSudhanshu's journey isn't just one of entrepreneurial success; it's also a story

In [11]:
splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=30)
docs = splitter.split_documents(document)

In [12]:
len(docs)

61

In [13]:
docs

[Document(metadata={'source': 'sudhanshuinfo.txt'}, page_content='Making an Impact\nHelping Millions of Students Succeed'),
 Document(metadata={'source': 'sudhanshuinfo.txt'}, page_content="Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students,"),
 Document(metadata={'source': 'sudhanshuinfo.txt'}, page_content='Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.'),
 Document(metadata={'source': 'sudhanshuinfo.txt'}, page_content='In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron co

In [14]:
texts = [doc.page_content for doc in docs]
texts

['Making an Impact\nHelping Millions of Students Succeed',
 "Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students,",
 'Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.',
 'In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.',
 "The Entrepreneur and Teacher: Sudhanshu's Dual Legacy",
 "Sudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Th

In [19]:
embeddings = [generate_embeddings(i) for i in texts]

KeyError: 'data'

In [16]:
generate_embeddings("my name is sudhanshu")

array([-0.00645238, -0.02682346, -0.02852873, ..., -0.00969585,
        0.01474829, -0.00714371], shape=(1536,))

In [18]:
generate_embeddings("This is a test input.")


array([ 0.02033959,  0.0112574 ,  0.01501457, ...,  0.0141459 ,
       -0.01669541, -0.00123944], shape=(1536,))

In [ ]:
  = []
valid_texts = []
for i ,text in enumerate(texts[0:8]):
    clean_text = text.strip()
    if not clean_text:
        print(f"Skipping empty text at index {i}")
        continue
    embedding = generate_embeddings(text)
    embeddings.append(embedding)
    valid_texts.append(text)embeddings
    print(f"Processed {i+1}/{len(texts)}: {text[:30]}... -> {embedding[:5]}")  # Print first 30 characters of text and first 5 elements of embedding

Processed 1/61: Making an Impact
Helping Milli... -> [ 0.03395454 -0.0469909   0.03878181  0.07887272  0.02695909]
Processed 2/61: Sudhanshu's commitment to affo... -> [-0.01364236  0.00639423  0.05721121  0.02440282  0.04653747]
Processed 3/61: Many of these students, like S... -> [-0.02204193 -0.00722562  0.00345266  0.03793968  0.04818918]
Processed 4/61: In 2022, iNeuron was acquired ... -> [-0.04330519 -0.05195538  0.02764536  0.0217475   0.03644469]
Processed 5/61: The Entrepreneur and Teacher: ... -> [0.01671011 0.01011956 0.04287479 0.01667061 0.00875009]
Processed 6/61: Sudhanshu's journey isn't just... -> [-0.00970297 -0.00214104  0.0598214   0.02851626  0.0276796 ]
Processed 7/61: in Big Data, Data Science, or ... -> [-0.00566224 -0.01421534  0.03512025 -0.01587579  0.05972831]
Processed 8/61: His commitment to affordable e... -> [ 0.01117547 -0.04308555  0.04391897  0.05712749  0.01579719]


In [28]:
embeddings

[array([ 0.03395454, -0.0469909 ,  0.03878181, ..., -0.02398636,
        -0.01851818,  0.01633636], shape=(1536,)),
 array([-0.01364236,  0.00639423,  0.05721121, ..., -0.00413274,
        -0.00975312, -0.00021493], shape=(1536,)),
 array([-0.02204193, -0.00722562,  0.00345266, ..., -0.00756314,
        -0.02643654, -0.00205438], shape=(1536,)),
 array([-0.04330519, -0.05195538,  0.02764536, ..., -0.03267549,
         0.01820879,  0.03354321], shape=(1536,)),
 array([ 0.01671011,  0.01011956,  0.04287479, ..., -0.04371754,
         0.01135734, -0.00684733], shape=(1536,)),
 array([-0.00970297, -0.00214104,  0.0598214 , ..., -0.01701214,
        -0.01090567,  0.00101315], shape=(1536,)),
 array([-0.00566224, -0.01421534,  0.03512025, ..., -0.00708975,
         0.00744215,  0.00205764], shape=(1536,)),
 array([ 0.01117547, -0.04308555,  0.04391897, ...,  0.00480482,
        -0.02457341,  0.01011475], shape=(1536,))]

In [29]:
import time
import numpy as np

embeddings = []

for i, text in enumerate(texts):
    try:
        print(f"🔄 Processing {i+1}/{len(texts)}...")
        embedding = generate_embeddings(text).astype('float32')
        embeddings.append(embedding)
        time.sleep(1)  # ⏳ Add delay to respect API rate limits
    except ValueError as e:
        print(f"❌ Error on text {i+1}: {e}")


🔄 Processing 1/61...
🔄 Processing 2/61...
🔄 Processing 3/61...
🔄 Processing 4/61...
🔄 Processing 5/61...
🔄 Processing 6/61...
🔄 Processing 7/61...
🔄 Processing 8/61...
🔄 Processing 9/61...
🔄 Processing 10/61...
🔄 Processing 11/61...


KeyError: 'data'

In [30]:
embeddings

[array([ 0.03395454, -0.0469909 ,  0.03878181, ..., -0.02398636,
        -0.01851818,  0.01633636], shape=(1536,), dtype=float32),
 array([-0.01364236,  0.00639423,  0.05721121, ..., -0.00413274,
        -0.00975312, -0.00021493], shape=(1536,), dtype=float32),
 array([-0.02204193, -0.00722562,  0.00345266, ..., -0.00756314,
        -0.02643654, -0.00205438], shape=(1536,), dtype=float32),
 array([-0.04330518, -0.05195538,  0.02764536, ..., -0.03267549,
         0.01820879,  0.03354321], shape=(1536,), dtype=float32),
 array([ 0.01671011,  0.01011956,  0.04287479, ..., -0.04371754,
         0.01135734, -0.00684733], shape=(1536,), dtype=float32),
 array([-0.00970297, -0.00214104,  0.0598214 , ..., -0.01701215,
        -0.01090567,  0.00101315], shape=(1536,), dtype=float32),
 array([-0.00568317, -0.01421538,  0.03512035, ..., -0.00705393,
         0.00747801,  0.00206959], shape=(1536,), dtype=float32),
 array([ 0.01117547, -0.04308555,  0.04391897, ...,  0.00480482,
        -0.0245734

In [31]:
import faiss
from langchain.vectorstores.faiss import FAISS
from langchain.docstore.document import Document

In [37]:
dimension = embeddings[0].shape[0]
faiss_index = faiss.IndexFlatL2(dimension)

faiss_index.add(np.array(embeddings).astype('float32'))

In [42]:
generate_response("tell me about sudhanshu")

{'id': 'chatcmpl-BVba4WXy4g3mcUWIcXBM4HX0oqKHh', 'object': 'chat.completion', 'created': 1746872329, 'model': 'gpt-4.1-nano', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': "Hello! Could you please provide more context or specify which Sudhanshu you're referring to? There may be multiple individuals with that name, or it could refer to a person, place, or something else. Providing additional details will help me give you accurate information."}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 25, 'completion_tokens': 54, 'total_tokens': 79}}


"Hello! Could you please provide more context or specify which Sudhanshu you're referring to? There may be multiple individuals with that name, or it could refer to a person, place, or something else. Providing additional details will help me give you accurate information."

In [43]:
from langchain.chains import RetrievalQA

In [ ]:
RetrievalQA.from_chain_type(llm,retrival)


In [49]:
document = [Document(page_content=text) for text in texts[:len(embeddings)]]

In [66]:
from langchain.vectorstores.faiss import FAISS
from langchain.docstore.document import Document
document = [Document(page_content=text) for text in texts[:len(embeddings)]]

import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS

faiss_index = faiss.IndexFlatL2(dimension)
vector_store = FAISS(
    embedding_function=generate_embeddings,
    index=faiss_index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)
vector_store.add_documents(document)

`embedding_function` is expected to be an Embeddings object, support for passing in a function will soon be removed.


['62c24928-d3fb-4612-bd1c-93e80e0c4f32',
 '2f48f22c-2c37-4a17-a737-d5aa68c736db',
 'a728f9ce-f880-463a-8fc6-78caf0181cd6',
 'db798df8-5897-4558-aa8e-1ca03ec05fe8',
 'cba424c8-8577-44fb-8b84-ce2cff35ec84',
 '869cd529-00ee-4fed-938b-0193a6a78bfc',
 '404d94b2-e935-47f7-a7cf-bff7c52f5776',
 '5a7882c0-ea39-404c-a458-e7c338dbbf35',
 '6947b238-6871-438b-9e35-61186bc1f421',
 '24c80ee9-52ad-474d-98d7-5fead56e58ae']

In [68]:
vector_store.save_local("faiss_index")

In [69]:
retriver = vector_store.as_retriever(search_kwargs={"k": 2})

In [70]:
from euriai import EuriaiLangChainLLM

llm = EuriaiLangChainLLM(
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNTM3YzM3Zi0xNmFkLTRjZTUtYjRhMC0wNTNjYTIyNzE1YTgiLCJlbWFpbCI6InN1ZGhhbnNodUBldXJvbi5vbmUiLCJpYXQiOjE3NDMyMzkyNTYsImV4cCI6MTc3NDc3NTI1Nn0.HRHeCucOK0hPVZQwyvNoD0GaHarvHNivjJ2l6-xU1HA",
    model="gpt-4.1-nano",
    temperature=0,
    max_tokens=300
)

print(llm.invoke("Write a poem about time travel."))

Through whispers of the ancient breeze,  
A traveler moves with silent ease,  
Beyond the bounds of present days,  
To chase the lost, forgotten rays.

With every tick, the clock unwinds,  
A bridge through eras, space, and minds,  
From dawn's first light to twilight's fade,  
In history’s shadows, softly played.

The future beckons with a gleam,  
A distant, shimmering dream,  
While echoes of the past remain,  
A haunting, sweet refrain.

Time’s gentle river flows and bends,  
A story woven without end,  
A dance of moments, swift and slow,  
Where all our hopes and fears do flow.

So, stand on the edge of what has been,  
And reach into what might have been,  
For time’s great secret, ever spun,  
Is only just begun.


In [73]:
rag_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever = retriver)

In [74]:
rag_chain("who is sudhanshu")

C:\Users\scl\AppData\Local\Temp\ipykernel_45756\2566710363.py:1: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  rag_chain("who is sudhanshu")


{'query': 'who is sudhanshu',
 'result': 'Sudhanshu is an individual known for his dedication to affordable education and his efforts to empower students through teaching. He has made significant contributions in fields such as Big Data and Data Science, and many students credit him with positively impacting their lives by helping them secure jobs and improve their skills.'}

In [75]:
generate_response("who is sudhanshu")

{'id': 'chatcmpl-BVc3adW2OclwQKKpNjdD5LtiKNKHU', 'object': 'chat.completion', 'created': 1746874159, 'model': 'gpt-4.1-nano', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '"Sudhanshu" is a common Indian given name, and without additional context, it\'s difficult to identify a specific individual. It could refer to various people such as professionals, students, or public figures. If you can provide more details or specify the context in which you\'re asking about Sudhanshu, I’d be happy to help you with more targeted information.'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 24, 'completion_tokens': 75, 'total_tokens': 99}}


'"Sudhanshu" is a common Indian given name, and without additional context, it\'s difficult to identify a specific individual. It could refer to various people such as professionals, students, or public figures. If you can provide more details or specify the context in which you\'re asking about Sudhanshu, I’d be happy to help you with more targeted information.'

In [76]:
rag_chain("give me the comapny whre sudhanshu is working")

{'query': 'give me the comapny whre sudhanshu is working',
 'result': "I don't know the name of the company where Sudhanshu is working based on the provided information."}