In [23]:
input = [3,4,5,6,7,6,7,5,6,7,8,9]
output = [3,4,5,56,6,7,8,9,0,0,7,4]

In [24]:
list(zip(input,output))

[(3, 3),
 (4, 4),
 (5, 5),
 (6, 56),
 (7, 6),
 (6, 7),
 (7, 8),
 (5, 9),
 (6, 0),
 (7, 0),
 (8, 7),
 (9, 4)]

In [25]:
w = 0.0
b= 0.0
lr = .01

In [26]:
for epoch in range(1000):
    total_loss = 0
    for x,y in zip(input,output):
        Y_pred = w*x+b
        error = Y_pred-y
        loss = error**2
        total_loss = total_loss + loss
        
        dw = 2*error*x
        db = 2*error
        
        w = w -lr*dw
        b = b - lr*db
        
    if epoch %10 ==0 :
        print(f"epoch {epoch} | Loss : {total_loss}  | w : {w} , b: {b}")
        
test_data = 7 
prediction = w*test_data + b 
print(prediction)   

epoch 0 | Loss : 4765.74205765353  | w : -0.02274495796089715 , b: 0.234673196595955
epoch 10 | Loss : 4741.506151986847  | w : -0.2521193533024988 , b: 2.4057629903058793
epoch 20 | Loss : 4727.5764121731045  | w : -0.45165831217269514 , b: 4.294452424910856
epoch 30 | Loss : 4720.637761491353  | w : -0.625242621998145 , b: 5.937474187862894
epoch 40 | Loss : 4718.521124029562  | w : -0.7762482841915561 , b: 7.3667830324367145
epoch 50 | Loss : 4719.645961229264  | w : -0.9076121732285329 , b: 8.610177258394142
epoch 60 | Loss : 4722.86919446392  | w : -1.021889155245383 , b: 9.691839354737802
epoch 70 | Loss : 4727.371905119765  | w : -1.1213017770443898 , b: 10.632806319391081
epoch 80 | Loss : 4732.5744895107555  | w : -1.2077834918966002 , b: 11.45137880294375
epoch 90 | Loss : 4738.073230935231  | w : -1.2830162628308601 , b: 12.163477033806155
epoch 100 | Loss : 4743.592978119958  | w : -1.3484632747468397 , b: 12.78295044707873
epoch 110 | Loss : 4748.951924222351  | w : -1.405

In [31]:
input = [1,2,3,4,5]
output = [2,4,6,8,10] 

In [32]:
w1 , b1 = .1,0.0
w2,b2 = -0.1 , 0.0
w3,w4 = .1 , .1 
b3 = 0.0
lr = .01

In [33]:
def relu(x):
    return max(0,x)

In [34]:
def relu_derivative(x):
    return 1 if x>0 else 0 

In [36]:
for epoch in range(100):
    total_loss = 0 
    for x,y in zip(input,output):
        z1 = w1*x + b1
        h1 = relu(z1)
        
        z2 = w2*x + b2
        h2 = relu(z2)
        
        Y_pred = w3*h1 + w4*h2 + b3
        
        error = Y_pred - y 
        loss  = error**2
        total_loss = total_loss + loss
        
        dl_dy = 2*error
        
        dw3 = dl_dy * h1
        dw4 = dl_dy * h2
        db3 = dl_dy
        
        dh1 = dl_dy * w3
        dh2 = dl_dy * w4
        
        dz1 = dh1* relu_derivative(z1)
        dz2 = dh2* relu_derivative(z2)
        
        dw1 = dz1 * x
        db1 = dz1
        
        dw2 = dz2 * x
        db2 = dz2
        
        w1 = w1 - lr*dw1
        w2 = w2 - lr*dw2
        w3 = w3 - lr*dw3
        w4 = w4 - lr*dw4
        
        
        b1 = b1 - lr*db1
        b2 = b2 - lr*db2
        b3 = b3 - lr*db3
        
    if epoch %10 ==0 :
        print(f"epoch {epoch} | Loss : {total_loss} ")
        
        
def prediction(x):
    z1 = w1*x + b1
    h1 = relu(z1)
        
    z2 = w2*x + b2
    h2 = relu(z2)
        
    y_output = w3*h1 + w4*h2 + b3
    return y_output     
                
prediction(9)     

epoch 0 | Loss : 197.58784675778605 
epoch 10 | Loss : 0.7822743866736906 
epoch 20 | Loss : 0.2777331306080438 
epoch 30 | Loss : 0.09441733364350127 
epoch 40 | Loss : 0.03110053083599192 
epoch 50 | Loss : 0.010038059173204952 
epoch 60 | Loss : 0.00320027527189278 
epoch 70 | Loss : 0.0010129806992875082 
epoch 80 | Loss : 0.0003193181207800499 
epoch 90 | Loss : 0.00010042211687133479 


17.99692772369434

In [37]:
import tensorflow as tf 
import numpy as np 

In [38]:
input

[1, 2, 3, 4, 5]

In [40]:
output

[2, 4, 6, 8, 10]

In [41]:
x = np.array(input,dtype=float)
y = np.array(output, dtype=float)

In [55]:
model = tf.keras.Sequential([tf.keras.layers.Dense(20,activation='relu',input_shape = [1]),
                    tf.keras.layers.Dense(1) ])

In [56]:
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=.001),loss='mean_squared_error')

In [68]:
model.fit(x,y,epochs=1000,verbose=1)
model.save("euron_gen_ai_first.h5")


Epoch 1/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0056
Epoch 2/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0056
Epoch 3/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0056
Epoch 4/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0056
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0056
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0056
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0055
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0055
Epoch 9/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0055
Epoch 10/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.0055
Epoch 11/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0055
Epoch 12/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 13/1000
1/1 [===========================

c:\Users\scl\OneDrive\Documents\projects\phitest\.conda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [69]:
model.save("euron_gen_ai_first.pb")

INFO:tensorflow:Assets written to: euron_gen_ai_first.pb\assets


INFO:tensorflow:Assets written to: euron_gen_ai_first.pb\assets


In [58]:
model.predict([90])

1/1 [==============================] - 0s 35ms/step


array([[175.81558]], dtype=float32)

In [79]:
data = 'help'
char2idx = {'h':0 , 'e' : 1 , "l":2 , "p" :3}
idx2char = {v : k for k , v in char2idx.items()}

In [80]:
char2idx

{'h': 0, 'e': 1, 'l': 2, 'p': 3}

In [81]:
idx2char

{0: 'h', 1: 'e', 2: 'l', 3: 'p'}

In [82]:
input_seq = [char2idx[c] for c in data[:-1]]
target_seq = [char2idx[c] for c in data [1:]]

In [83]:
target_seq

[1, 2, 3]

In [84]:

input_seq

[0, 1, 2]

In [85]:
x = tf.one_hot(input_seq,depth=4 )
x = tf.expand_dims(x , axis=0)
y = tf.expand_dims(target_seq , axis=0)

In [86]:
x

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

In [87]:
y

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [88]:
model = tf.keras.Sequential([tf.keras.layers.LSTM(8,return_sequences=True , input_shape =(3,4) ) , 
                     tf.keras.layers.Dense(4,activation='linear')])

In [89]:
model.compile(optimizer='adam' ,loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [91]:
for epoch in range(201):
    model.train_on_batch(x,y)
    
    if epoch % 50  == 0 :
        output = model(x)
        print(output)
        pred = tf.argmax(output,axis = -1).numpy()[0]
        pred_char = "".join([idx2char[i] for i in pred] )
        print(f"epoch : {epoch} , prediction : {pred_char} , loss : {loss} ")

tf.Tensor(
[[[-0.43052647  0.6293929   0.40136704  0.00332764]
  [-0.9845111   0.31151864  1.2894262   0.7987659 ]
  [-1.1662571  -0.27864686  1.0258137   1.5824367 ]]], shape=(1, 3, 4), dtype=float32)
epoch : 0 , prediction : elp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.5468945   0.87273     0.44815248 -0.1333274 ]
  [-1.3161606   0.40613034  1.7407258   0.84756476]
  [-1.4110458  -0.48194915  0.8636982   2.1599348 ]]], shape=(1, 3, 4), dtype=float32)
epoch : 50 , prediction : elp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.6647454   1.1562295   0.4451491  -0.30842942]
  [-1.596593    0.5144413   2.2648385   0.7755447 ]
  [-1.4807738  -0.6536855   0.6780906   2.649841  ]]], shape=(1, 3, 4), dtype=float32)
epoch : 100 , prediction : elp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.7775857   1.4494135   0.38885826 -0.47411406]
  [-1.8080274   0.59139127  2.728506    0.68132603]
  [-1.4915437  -0.7973065   0.53581935  3.0443847 ]]], shape=(1, 3, 4), dtype=float32)
epoch 

In [92]:
model.save('euron_lstm.h5')

c:\Users\scl\OneDrive\Documents\projects\phitest\.conda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
