In [4]:
# Using requests library for embeddings
import requests
import numpy as np

def generate_embeddings():
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNTM3YzM3Zi0xNmFkLTRjZTUtYjRhMC0wNTNjYTIyNzE1YTgiLCJlbWFpbCI6InN1ZGhhbnNodUBldXJvbi5vbmUiLCJpYXQiOjE3NDMyMzkyNTYsImV4cCI6MTc3NDc3NTI1Nn0.HRHeCucOK0hPVZQwyvNoD0GaHarvHNivjJ2l6-xU1HA"
    }
    payload = {
        "input": "The food was delicious and the service was excellent.",
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()

    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    print(f"Generated embedding with shape: {embedding.shape}")
    print(f"First 5 values: {embedding}")
    
    # Example: Calculate vector norm
    norm = np.linalg.norm(embedding)
    print(f"Vector norm: {norm}")
    
    return embedding



In [5]:
generate_embeddings()

Generated embedding with shape: (1536,)
First 5 values: [-0.03244253 -0.00839565 -0.06356495 ... -0.00225143  0.05896459
 -0.03152246]
Vector norm: 1.0000000296607552


array([-0.03244253, -0.00839565, -0.06356495, ..., -0.00225143,
        0.05896459, -0.03152246], shape=(1536,))

In [6]:
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNTM3YzM3Zi0xNmFkLTRjZTUtYjRhMC0wNTNjYTIyNzE1YTgiLCJlbWFpbCI6InN1ZGhhbnNodUBldXJvbi5vbmUiLCJpYXQiOjE3NDMyMzkyNTYsImV4cCI6MTc3NDc3NTI1Nn0.HRHeCucOK0hPVZQwyvNoD0GaHarvHNivjJ2l6-xU1HA"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()

    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    print(f"Generated embedding with shape: {embedding.shape}")
    print(f"First 5 values: {embedding}")
    
    # Example: Calculate vector norm
    norm = np.linalg.norm(embedding)
    print(f"Vector norm: {norm}")
    
    return embedding

In [8]:
data1 = generate_embeddings("my name is sudhanshu kumar")

Generated embedding with shape: (1536,)
First 5 values: [-0.00965959 -0.02545136 -0.0277467  ...  0.00493669  0.01804773
 -0.00078129]
Vector norm: 1.0000000358807721


In [10]:
data1


array([-0.00965472, -0.02549836, -0.02770387, ...,  0.00487237,
        0.01802664, -0.00078276], shape=(1536,))

In [11]:
data2 = generate_embeddings("sudhanshu kumar take class for tech")

Generated embedding with shape: (1536,)
First 5 values: [-0.04761439  0.00904443  0.00276002 ...  0.02080091  0.02366648
  0.00042776]
Vector norm: 0.9999999749828703


In [12]:
data2

array([-0.04761439,  0.00904443,  0.00276002, ...,  0.02080091,
        0.02366648,  0.00042776], shape=(1536,))

In [13]:
import numpy as np 

In [14]:
data1 ,data2

(array([-0.00965472, -0.02549836, -0.02770387, ...,  0.00487237,
         0.01802664, -0.00078276], shape=(1536,)),
 array([-0.04761439,  0.00904443,  0.00276002, ...,  0.02080091,
         0.02366648,  0.00042776], shape=(1536,)))

In [16]:
cosign_similarty = np.dot(data1,data2)/(np.linalg.norm(data1)*np.linalg.norm(data2))

In [17]:
cosign_distance = 1- cosign_similarty

In [18]:
cosign_distance

np.float64(0.44584817411481026)

In [19]:
data3 = generate_embeddings("people call me by my name sudhanshu kumar")

Generated embedding with shape: (1536,)
First 5 values: [ 0.02695428 -0.05315723 -0.00928021 ...  0.0039504   0.01880695
  0.00535622]
Vector norm: 1.0000000276464485


In [20]:
data1, data2, data3

(array([-0.00965472, -0.02549836, -0.02770387, ...,  0.00487237,
         0.01802664, -0.00078276], shape=(1536,)),
 array([-0.04761439,  0.00904443,  0.00276002, ...,  0.02080091,
         0.02366648,  0.00042776], shape=(1536,)),
 array([ 0.02695428, -0.05315723, -0.00928021, ...,  0.0039504 ,
         0.01880695,  0.00535622], shape=(1536,)))

In [21]:
cosign_similarty2 = np.dot(data1,data3)/(np.linalg.norm(data1)*np.linalg.norm(data3))

In [22]:
cosign_similarty2

np.float64(0.829507737457489)

In [23]:
1-cosign_similarty2

np.float64(0.17049226254251104)

In [ ]:
dist - data 1 and data2 - 0.44584817411481026
dist data1 data 3 - .17049226254251104

In [1]:
import os
import requests
from chromadb import HttpClient
from dotenv import load_dotenv
load_dotenv()

EURI_API_KEY = os.getenv("EURI_API_KEY")

client = HttpClient(host="localhost",port = 8000)
collection = client.get_or_create_collection("sudh_euron_data")
collection

ModuleNotFoundError: No module named 'chromadb'

In [2]:
pip install chromadb

  Using cached chromadb-1.0.7-cp39-abi3-win_amd64.whl.metadata (7.0 kB)
  Using cached build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
  Using cached chroma_hnswlib-0.7.6-cp310-cp310-win_amd64.whl.metadata (262 bytes)
  Using cached fastapi-0.115.9-py3-none-any.whl.metadata (27 kB)
  Using cached uvicorn-0.34.2-py3-none-any.whl.metadata (6.5 kB)
  Using cached posthog-4.0.0-py2.py3-none-any.whl.metadata (3.0 kB)
  Using cached onnxruntime-1.21.1-cp310-cp310-win_amd64.whl.metadata (4.9 kB)
  Using cached opentelemetry_api-1.32.1-py3-none-any.whl.metadata (1.6 kB)
  Using cached opentelemetry_exporter_otlp_proto_grpc-1.32.1-py3-none-any.whl.metadata (2.5 kB)
  Using cached opentelemetry_instrumentation_fastapi-0.53b1-py3-none-any.whl.metadata (2.2 kB)
  Using cached opentelemetry_sdk-1.32.1-py3-none-any.whl.metadata (1.6 kB)
  Using cached tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
  Using cached pypika-0.48.9-py2.py3-none-any.whl
  Using cached overrides-7.7.0-py3-